export const ADD_RECORD = "ADD_RECORD";
export const UPDATE_RECORD = "UPDATE_RECORD";
export const EDIT_RECORD = "EDIT_RECORD";
export const DELETE_RECORD = "DELETE_RECORD";
export const SELECT_RECORD = "SELECT_RECORD";
export const SELECT_RECORDS = "SELECT_RECORDS";